site_name: VisualAlgo
site_url: https://tonyfu97.github.io/VisualAlgo/
site_description: vision-related algorithms and models
site_author: Tony Fu

repo_url: https://github.com/tonyfu97/VisualAlgo/
edit_uri: blob/master/docs/

theme:
    name: readthedocs
    locale: en
    analytics: {gtag: 'G-274394082'}
    highlightjs: true
    hljs_languages:
        - yaml
        - django
    features:
      - content.codehilite
      - content.code.copy

nav:
    - Home: index.md
    - Getting Started: pages/getting-started.md
    - Matrix: pages/matrix.md
    - Stimulus: pages/stimulus.md
    - 1. Image Pre-processing and Enhancement: pages/image-preprocessing-and-enhancement.md
    - 2. Feature Extraction: pages/feature-extraction.md
    - 3. Segmentation and Grouping: pages/segmentation-and-grouping.md
    - 4. Object Detection and Recognition: pages/object-detection-and-recognition.md
    - 5. Motion Analysis and Tracking: pages/motion-analysis-and-tracking.md
    - 6. Depth Perception and 3D Reconstruction: pages/depth-perception-and-3d-reconstruction.md
    - 7. Color Vision: pages/color-vision.md
    - 8. Attention and Search: pages/attention-and-search.md
    - 9. Learning and Memory: pages/learning-and-memory.md



copyright: Copyright &copy; 2023 Tony Fu

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math
